name: rocprofiler-systems Debian (GCC, Python, ROCm)
run-name: debian
on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  debian:
    runs-on: ubuntu-latest
    container:
      image: dgaliffiamd/rocprofiler-systems:ci-base-debian-12
    steps:
    - name: Free Container Space
      run: |
        echo "Disk usage before cleanup:"
        df -h

        du -a /__e | sort -n -r | head -n 10
  
        # Clean package cache
        apt-get clean
        apt-get autoclean
        
        rm -rf /usr/share/dotnet || true
        rm -rf /usr/local/lib/android || true
        rm -rf "$AGENT_TOOLSDIRECTORY" || true
        
        # Remove unnecessary packages if any were installed
        apt-get autoremove -y
        apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [sudo apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
        apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y '^llvm-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^llvm-.*' --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
        apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
        apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
        apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
        
        # Clean temporary files
        rm -rf /tmp/*
        rm -rf /var/tmp/*
  
        echo "Disk usage after cleanup:"
        df -h
