name: rocprofiler-systems Debian (GCC, Python, ROCm)
run-name: debian
on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  debian:
    runs-on: ubuntu-latest
    container:
      image: dgaliffiamd/rocprofiler-systems:ci-base-debian-12
    steps:
    - name: Free Container Space
      run: |
        echo "Disk usage before cleanup:"
        df -h

        du -a /__e | sort -n -r | head -n 10
        rm -rf /__e/node24*
        rm -rf /__e/node20*
  
        echo "Disk usage after cleanup:"
        df -h
